'use strict';

define(function() {
  return {

    H  : { radius : 53 },   
    He : { radius : 31 }, 
    Li : { radius : 167 },
    Be : { radius : 112 },
    B  : { radius : 87 },
    C  : { radius : 67 },
    N  : { radius : 56 },
    O  : { radius : 48 },
    F  : { radius : 42 },
    Ne : { radius : 38 },
    Na : { radius : 190 },
    Mg : { radius : 145 },
    Al : { radius : 118 },
    Si : { radius : 111 },
    P  : { radius : 98 },
    S  : { radius : 88 },
    Cl : { radius : 79 },
    Ar : { radius : 71 },
    K  : { radius : 243 },
    Ca : { radius : 194 },
    Sc : { radius : 184 },
    Ti : { radius : 176 },
    V  : { radius : 171 },
    Cr : { radius : 166 },
    Mn : { radius : 161 },
    Fe : { radius : 156 },
    Co : { radius : 152 },
    Ni : { radius : 149 },
    Cu : { radius : 145 },
    Zn : { radius : 142 },
    Ga : { radius : 136 },
    Ge : { radius : 125 },
    As : { radius : 114 },
    Se : { radius : 103 },
    Br : { radius : 94 },
    Kr : { radius : 88 },
    Rb : { radius : 265 },
    Sr : { radius : 219 },
    Y  : { radius : 212 },
    Zr : { radius : 206 },
    Nb : { radius : 198 },
    Mo : { radius : 190 },
    Tc : { radius : 183 },
    Ru : { radius : 178 },
    Rh : { radius : 173 },
    Pd : { radius : 169 },
    Ag : { radius : 165 },
    Cd : { radius : 161 },
    In : { radius : 156 },
    Sn : { radius : 145 },
    Te : { radius : 123 },
    I  : { radius : 115 },
    Xe : { radius : 108 },
    Cs : { radius : 298 },
    Ba : { radius : 253 },
    La : { radius : 195 },
    Ce : { radius : 185 },
    Pr : { radius : 247 },
    Nd : { radius : 206 },
    Pm : { radius : 205 },
    Sm : { radius : 238 },
    Eu : { radius : 231 },
    Gd : { radius : 233 },
    Tb : { radius : 225 },
    Dy : { radius : 228 },
    Ho : { radius : 175 },
    Er : { radius : 226 },
    Tm : { radius : 222 },
    Yb : { radius : 222 },
    Lu : { radius : 217 },
    Hf : { radius : 208 },
    Ta : { radius : 200 },
    W  : { radius : 193 },
    Re : { radius : 188 },
    Os : { radius : 185 },
    Ir : { radius : 180 },
    Pt : { radius : 177 },
    Au : { radius : 174 },
    Hg : { radius : 171 },
    Tl : { radius : 156 },
    Pb : { radius : 154 },
    Bi : { radius : 143 },
    Po : { radius : 135 },
    At : { radius : 100 },
    Rn : { radius : 120 },
    Fr : { radius : 100 },
    Ra : { radius : 215 },
    Ac : { radius : 195 },
    Th : { radius : 180 },
    Pa : { radius : 190 },
    U  : { radius : 175 },
    Np : { radius : 175 },
    Pu : { radius : 175 },
    Am : { radius : 175 },
    Cm : { radius : 0 },
    Bk : { radius : 0 },
    Cf : { radius : 0 },
    Es : { radius : 0 },
    Fm : { radius : 0 },
    Md : { radius : 0 },
    No : { radius : 0 },
    Lr : { radius : 0 },
    Rf : { radius : 0 },
    Db : { radius : 0 },
    Sg : { radius : 0 },
    Bh : { radius : 0 },
    Hs : { radius : 0 },
    Mt : { radius : 0 },
    Ds : { radius : 0 },
    Rg : { radius : 0 },
    Cn : { radius : 0 },
    Uut: { radius : 0 },
    Fl : { radius : 0 },
    Uup: { radius : 0 },
    Lv : { radius : 0 },
    Uus: { radius : 0 },
    Uuo: { radius : 0 },
     


  };
});
